services:
#    pages.example:
#        class: Admin\PagesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     Admin\PagesBundle\Controller\:
        resource: '../../../../../src/Admin/PagesBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
