admin_images:
    resource: "@ImagesBundle/Controller/"
    type:     annotation
    prefix:   /admin/image-manager

pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /admin/page-manager

signin:
    resource: "@SigninBundle/Controller/"
    type:     annotation
    prefix:   /signin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
